import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Particles',
  description: 'A mesmerizing visualization of Perlin noise, where thousands of particles flow like a fluid river across the screen, driven by invisible mathematical vectors.',
  author: 'User',
  tags: ['generative', 'perlin-noise', 'flow-field', 'particles', 'canvas', 'simulation', 'nature'],
  defaultProps: {
    scale: 0.001,
    cellSize: 20,
    radius: 2,
    fieldSpeed: 0.0005,
    particleSpeed: 2,
    particleCount: 1400,
    backgroundColor: '#4169e1',
    particleColor: '#ffffff'
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#4169e1',
      description: 'The background color of the canvas.',
    },
    {
      key: 'particleColor',
      label: 'Particle Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'The color of the flowing particles.',
    },
    {
      key: 'particleCount',
      label: 'Particle Count',
      type: 'slider',
      min: 100,
      max: 5000,
      step: 100,
      defaultValue: 1400,
      description: 'The number of particles flowing in the field.',
    },
    {
      key: 'particleSpeed',
      label: 'Particle Speed',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 2,
      description: 'How fast particles move across the canvas.',
    },
    {
      key: 'radius',
      label: 'Particle Size',
      type: 'slider',
      min: 1,
      max: 10,
      step: 0.5,
      defaultValue: 2,
      description: 'The radius of individual particles.',
    },
    {
      key: 'scale',
      label: 'Noise Scale',
      type: 'slider',
      min: 0.0001,
      max: 0.01,
      step: 0.0001,
      defaultValue: 0.001,
      description: 'Zoom level of the noise pattern. Lower values make smoother, larger curves.',
    },
    {
      key: 'cellSize',
      label: 'Grid Cell Size',
      type: 'slider',
      min: 10,
      max: 100,
      step: 5,
      defaultValue: 20,
      description: 'The resolution of the underlying flow grid. Smaller cells = more detailed flow.',
    },
    {
      key: 'fieldSpeed',
      label: 'Field Evolution Speed',
      type: 'slider',
      min: 0.0001,
      max: 0.005,
      step: 0.0001,
      defaultValue: 0.0005,
      description: 'How fast the noise field changes shape (if animated).',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
