import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Wavy Bent Lines',
  description: 'An animated background featuring fluid, bent lines that undulate with wave-like motion, responding dynamically to mouse movements by contracting or diverging.',
  author: 'NetMods',
  tags: ['animated', 'bent-lines', 'waves', 'fluid', 'motion', 'interactive', 'abstract', 'geometric'],
  defaultProps: {
    backgroundColor: '#000000',
    lineColor: '#FFFFFF',
    gap: 25,
    radius: 160,
    force: 6,
    gravity: 0.3,
    waveSpeed: 8000,
    mouseInteraction: 'smear',
    effects: "wind"
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The overall background color of the canvas.',
    },
    {
      key: 'lineColor',
      label: 'Line Color',
      type: 'color',
      defaultValue: '#FFFFFF',
      description: 'The color of the bent lines in the animation.',
    },
    {
      key: 'gap',
      label: 'Line Gap',
      type: 'slider',
      min: 20,
      max: 200,
      step: 5,
      defaultValue: 25,
      description: 'The spacing (gap) between the bent lines in the canvas.',
    },
    {
      key: 'radius',
      label: 'Bend Radius',
      type: 'slider',
      min: 50,
      max: 500,
      step: 10,
      defaultValue: 160,
      description: 'The radius controlling the curvature and bend of the lines.',
    },
    {
      key: 'force',
      label: 'Force',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 6,
      description: 'The intensity of the wave-like forces affecting line movement.',
    },
    {
      key: 'gravity',
      label: 'Gravity',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.3,
      description: 'The gravitational pull influencing the downward drift of the lines.',
    },
    {
      key: 'waveSpeed',
      label: 'Wave Speed',
      type: 'slider',
      min: 0,
      max: 10000,
      step: 100,
      defaultValue: 8000,
      description: 'The speed at which wave-like motions propagate through the lines.',
    },
    {
      key: 'mouseInteraction',
      label: 'Mouse Effect',
      type: 'select',
      options: ['none', 'smear', 'converge', 'diverge'],
      defaultValue: 'smear',
      description: 'The interaction mode for mouse movements: none (no effect), smear (blurring trail), converge (lines pull toward mouse), or diverge (lines push away from mouse).',
    },
    {
      key: 'effects',
      label: 'General Effect',
      type: 'select',
      options: ['none', 'wind', 'waves'],
      defaultValue: 'wind',
      description: 'Global animation effect: none (static), wind (gentle horizontal drift), or waves (undulating vertical motion).',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
